server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: edna-biodiversity-pipeline
  datasource:
    url: jdbc:postgresql://localhost:5432/edna_biodiversity
    username: ${DB_USERNAME:edna_user}
    password: ${DB_PASSWORD:edna_password}
  jpa:
    hibernate:
      ddl-auto: update  # Using update for development, change to validate in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.edna.biodiversity: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 1 day in milliseconds

# Custom application properties
edna:
  pipeline:
    markers:
      - 18S
      - COI
    confidence-levels:
      - HIGH
      - MEDIUM
      - LOW
      - POTENTIALLY_NOVEL
