spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edna_biodiversity_test
    username: ${DB_USERNAME:edna_user}
    password: ${DB_PASSWORD:edna_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
